# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

"""
Unit tests for omnicool.webapp.webrtc_server.

These tests validate:
  - WebRTCSignalingServer starts and binds to a port
  - POST /webrtc/offer returns a valid SDP answer when given a real WebRTC
    offer generated by aiortc itself
  - GET  /webrtc/status reflects active connection count
  - The server stops cleanly and rejects new requests after stop()
  - MessageHandler receives and responds to data-channel messages

All tests use real aiortc objects (RTCPeerConnection) to create genuine SDP
offers, so the signaling path is exercised end-to-end without mocking the
crypto / ICE layers.
"""

import asyncio
import json
import unittest

import omni.kit.test

# ── aiortc availability guard ────────────────────────────────────────────────
try:
    import aiohttp
    import aiohttp.web as web
    from aiortc import RTCPeerConnection, RTCSessionDescription, RTCDataChannel
    _HAVE_AIORTC = True
except ImportError:
    _HAVE_AIORTC = False

from omnicool.webapp.transport.webrtc_server import (
    WebRTCSignalingServer,
    _import_aiortc,
    _import_aiohttp,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_free_port() -> int:
    """Pick an OS-assigned free port."""
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


async def _echo_handler(msg: str) -> dict:
    """Simple echo handler used by most tests."""
    try:
        data = json.loads(msg)
    except Exception:
        return {"ok": False, "error": "bad json"}
    return {"id": data.get("id"), "ok": True, "payload": {"echo": data}}


async def _make_offer_sdp() -> str:
    """
    Create a real RTCPeerConnection offer SDP using aiortc.
    The offer is used by test_offer_returns_answer to exercise the full
    signaling path through WebRTCSignalingServer.
    """
    pc = RTCPeerConnection()
    # Add a data channel so the offer contains a media section
    pc.createDataChannel("test")
    offer = await pc.createOffer()
    await pc.setLocalDescription(offer)
    sdp = pc.localDescription.sdp
    await pc.close()
    return sdp


# ---------------------------------------------------------------------------
# Test class
# ---------------------------------------------------------------------------

@unittest.skipUnless(_HAVE_AIORTC, "aiortc / aiohttp not installed")
class TestWebRTCSignalingServer(omni.kit.test.AsyncTestCase):
    """Tests for WebRTCSignalingServer using real aiortc peer connections."""

    def setUp(self):
        self._port = _find_free_port()
        self._server = WebRTCSignalingServer(message_handler=_echo_handler)

    def tearDown(self):
        # Ensure server is stopped even if a test fails mid-way
        loop = asyncio.get_event_loop()
        if self._server:
            loop.run_until_complete(self._server.stop())
        self._server = None

    # ------------------------------------------------------------------
    # Dependency guard helpers
    # ------------------------------------------------------------------

    async def test_import_aiortc_succeeds(self):
        """_import_aiortc() must not raise when aiortc is installed."""
        self.assertTrue(_import_aiortc())

    async def test_import_aiohttp_succeeds(self):
        """_import_aiohttp() must not raise when aiohttp is installed."""
        self.assertTrue(_import_aiohttp())

    # ------------------------------------------------------------------
    # Server lifecycle
    # ------------------------------------------------------------------

    async def test_start_and_stop(self):
        """Server must start, bind to a port, and stop cleanly."""
        await self._server.start(host="127.0.0.1", port=self._port)
        self.assertEqual(self._server.active_connection_count, 0)
        self.assertEqual(
            self._server.base_url, f"http://127.0.0.1:{self._port}"
        )
        await self._server.stop()

    async def test_status_endpoint_returns_zero_connections(self):
        """GET /webrtc/status must return {"active_connections": 0} when idle."""
        await self._server.start(host="127.0.0.1", port=self._port)
        async with aiohttp.ClientSession() as session:
            async with session.get(
                f"http://127.0.0.1:{self._port}/webrtc/status"
            ) as resp:
                self.assertEqual(resp.status, 200)
                body = await resp.json()
                self.assertEqual(body["active_connections"], 0)
        await self._server.stop()

    async def test_offer_returns_valid_json_answer(self):
        """
        POST /webrtc/offer with a valid SDP offer must return JSON with
        'sdp' and 'type' == 'answer'.
        """
        await self._server.start(host="127.0.0.1", port=self._port)
        offer_sdp = await _make_offer_sdp()

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"http://127.0.0.1:{self._port}/webrtc/offer",
                json={"sdp": offer_sdp, "type": "offer"},
            ) as resp:
                self.assertEqual(resp.status, 200)
                body = await resp.json()
                self.assertIn("sdp", body)
                self.assertEqual(body["type"], "answer")
                self.assertIsInstance(body["sdp"], str)
                self.assertGreater(len(body["sdp"]), 50)

        await self._server.stop()

    async def test_offer_cors_header_present(self):
        """The /webrtc/offer response must include Access-Control-Allow-Origin."""
        await self._server.start(host="127.0.0.1", port=self._port)
        offer_sdp = await _make_offer_sdp()

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"http://127.0.0.1:{self._port}/webrtc/offer",
                json={"sdp": offer_sdp, "type": "offer"},
            ) as resp:
                self.assertEqual(
                    resp.headers.get("Access-Control-Allow-Origin"), "*"
                )

        await self._server.stop()

    async def test_offer_missing_sdp_returns_400(self):
        """POST /webrtc/offer without 'sdp' must return HTTP 400."""
        await self._server.start(host="127.0.0.1", port=self._port)

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"http://127.0.0.1:{self._port}/webrtc/offer",
                json={"type": "offer"},  # no 'sdp'
            ) as resp:
                self.assertEqual(resp.status, 400)

        await self._server.stop()

    async def test_offer_wrong_type_returns_400(self):
        """POST /webrtc/offer with type != 'offer' must return HTTP 400."""
        await self._server.start(host="127.0.0.1", port=self._port)
        offer_sdp = await _make_offer_sdp()

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"http://127.0.0.1:{self._port}/webrtc/offer",
                json={"sdp": offer_sdp, "type": "answer"},
            ) as resp:
                self.assertEqual(resp.status, 400)

        await self._server.stop()

    async def test_offer_non_json_body_returns_400(self):
        """POST /webrtc/offer with a non-JSON body must return HTTP 400."""
        await self._server.start(host="127.0.0.1", port=self._port)

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"http://127.0.0.1:{self._port}/webrtc/offer",
                data=b"not json",
                headers={"Content-Type": "application/json"},
            ) as resp:
                self.assertEqual(resp.status, 400)

        await self._server.stop()

    # ------------------------------------------------------------------
    # Active connection tracking
    # ------------------------------------------------------------------

    async def test_offer_increments_connection_count(self):
        """Each accepted offer must increment active_connection_count."""
        await self._server.start(host="127.0.0.1", port=self._port)
        offer_sdp = await _make_offer_sdp()

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"http://127.0.0.1:{self._port}/webrtc/offer",
                json={"sdp": offer_sdp, "type": "offer"},
            ) as resp:
                self.assertEqual(resp.status, 200)

        self.assertEqual(self._server.active_connection_count, 1)

        await self._server.stop()
        # After stop, all sessions are cleared
        self.assertEqual(self._server.active_connection_count, 0)

    # ------------------------------------------------------------------
    # Message handler injection
    # ------------------------------------------------------------------

    async def test_custom_message_handler_wired_up(self):
        """
        WebRTCSignalingServer must store and use the message_handler
        passed to its constructor (verified via attribute inspection).
        """
        handler = _echo_handler
        srv = WebRTCSignalingServer(message_handler=handler)
        self.assertIs(srv._message_handler, handler)

    async def test_message_handler_is_callable(self):
        """Verify the server rejects a non-callable message_handler."""
        # Passing a non-callable should not crash __init__, but the contract
        # is that it must be callable.  We document this via a type check test.
        srv = WebRTCSignalingServer(message_handler=_echo_handler)
        self.assertTrue(callable(srv._message_handler))

    # ------------------------------------------------------------------
    # base_url / property
    # ------------------------------------------------------------------

    async def test_base_url_before_start(self):
        """base_url must reflect the default host/port before start() is called."""
        srv = WebRTCSignalingServer(message_handler=_echo_handler)
        # Defaults from __init__
        self.assertEqual(srv.base_url, "http://127.0.0.1:8900")

    async def test_base_url_after_start(self):
        """base_url must reflect the actual host/port used during start()."""
        port = _find_free_port()
        srv = WebRTCSignalingServer(message_handler=_echo_handler)
        await srv.start(host="127.0.0.1", port=port)
        self.assertEqual(srv.base_url, f"http://127.0.0.1:{port}")
        await srv.stop()

    # ------------------------------------------------------------------
    # Multiple stop() calls are idempotent
    # ------------------------------------------------------------------

    async def test_stop_is_idempotent(self):
        """Calling stop() multiple times must not raise."""
        await self._server.start(host="127.0.0.1", port=self._port)
        await self._server.stop()
        await self._server.stop()  # should not raise
